spring.application.name=blog
server.port=3000
debug=true

spring.datasource.url=jdbc:postgresql://ep-silent-dream-aiz2z687-pooler.c-4.us-east-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_XNvzB1TlfP5O

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

